
import {
  HelpCircle,
  Lightbulb,
  Frown,
  Smile,
  FileWarning,
  type LucideIcon,
  LogIn,
  UserPlus,
  Paperclip,
  LoaderCircle,
  WandSparkles,
  Send,
  KeyRound,
  Users,
  FileText,
  Network,
  Waypoints,
  Wrench,
  Building,
  ClipboardList,
  FileCheck2,
  Edit,
  FileUp,
  Trash2,
  FileImage,
  FileAudio,
  BookUser,
  FilePlus,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  Reclamo: FileWarning,
  Consulta: HelpCircle,
  Sugerencia: Lightbulb,
  Queja: Frown,
  Felicitacion: Smile,
  Login: LogIn,
  Register: UserPlus,
  Attach: Paperclip,
  Loading: LoaderCircle,
  Sparkles: WandSparkles,
  Submit: Send,
  Key: KeyRound,
  Users: Users,
  FileText: FileText,
  FileImage: FileImage,
  FileAudio: FileAudio,
  Network: Network,
  Waypoints: Waypoints,
  Wrench: Wrench,
  Building: Building,
  Survey: ClipboardList,
  Detail: FileCheck2,
  FAQ: HelpCircle,
  Edit: Edit,
  FileUp: FileUp,
  Trash2: Trash2,
  BookUser: BookUser,
  FilePlus: FilePlus,
};
